### ISSUE TITLE
Got ServiceProvider error

### ISSUE THREAD

**Issue by azulkipli** [DraperStudio/Laravel-Countries#1]
Im using laravel 5.1, followed readme but Got ServiceProvider error

``
Class 'DraperStudio\Countries\CountriesServiceProvider' not found in /Users/azul/WebRoot/ulin/shopeya/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php
``

**Comment by DraperStudio** [comment]
`CountriesServiceProvider` has been changed to `ServiceProvider`.
