### ISSUE TITLE
Relevance is removed

### ISSUE THREAD

**Issue by coldKingdom** [DraperStudio/Laravel-Countries#1]
The relevance field is removed from mledoze/countries 1.7.0, which breaks the seeder.

**Comment by DraperStudio** [comment]
Just checked and the relevance field is still available in 1.7.0.

**Comment by coldKingdom** [comment]
Are you sure?
This commit removes it: https://github.com/mledoze/countries/commit/d92f078c5ff71c330a7d9a33c4d4cb066c168faf

Added your package to my project yesterday and I got an error on the relevance-field when I tried to seed it to my database.

**Comment by DraperStudio** [comment]
Hmm, downloaded the 1.7.0 zip archive and in the files from it the relevance field is still available.

I will push a fix within the next 10 minutes.

**Comment by DraperStudio** [comment]
Fix pushed https://github.com/DraperStudio/Laravel-Countries/commit/d41b742bd8b6bdcc0ba85b9be4a8b60d9390ffe1 and v1.0.2 tagged.

Try again

**Comment by coldKingdom** [comment]
Works like a charm! Thank you!
